### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by scj643** [Sinap/funimationlater#4]
Was wondering if you use IRC and if we could have a channel to bounce ideas and work with debugging.

**Comment by afrase** [comment]
I haven't used IRC in a long time but I did create a Slack which is a lot like IRC. https://funimationlater.slack.com

**Comment by afrase** [comment]
actually it's https://funimationlaterteam.slack.com

**Comment by scj643** [comment]
It says I need to be invited

**Comment by afrase** [comment]
What's your email?

**Comment by scj643** [comment]
surettcharles at gmail.com
